openapi: '3.0.3'
info:
  title: Shared Endpoints
  version: '0.0.0'
paths:
  /health:
    get:
      tags:
        - Health
      summary: Health Check
      responses:
        '200':
          description: Server is healthy
