info:
  contact: {}
  description: API Abstraction of common web-server duties providing re-use capabilities.
  license:
    name: GNU General Public License v3.0
    url: https://www.gnu.org/licenses/gpl-3.0.html
  title: SharedDeps Server
  version: v0.0.0
paths: {}
swagger: "2.0"
